### ISSUE TITLE
Add petclinic application analyze test

### ISSUE THREAD

**Issue by aufi** [konveyor/go-konveyor-tests#2]
## Introduction

Petclinic is a demo application example including analysis with custom rules. It should be added to go konveyor tests analyzing the application with custom rules focusing on Hazelcast distributed session store.

## Description

Added Petclinic analysis test case: https://github.com/konveyor/go-konveyor-tests/blob/main/analysis/test_cases.go#L132-L250

Analysis testing method was updated with Rulesets, Issues parsing and few minor updates and parallel analysis test execution is possible now. 

```[tasklist]
### Tasks
- [x] Add petclinic to basic test
- [x] Add custom rules support to binding
- [x] Run petclinic analysis with hazelcast custom rules (demo on community call)
- [ ] Finish parsing windup to lsp/dynamic reports output format including incidents
```

## Resources
Linking Savitha's docs @savitharaghunathan
- https://hackmd.io/eJ02vUbASp6ls84wzLUOSw?view
- https://docs.google.com/presentation/d/1sR0VpM8jQ4iqDYc_FL5NXFlnqhnqFzbAgGqaH2oTPTk
